# Generated by Django 5.2.6 on 2025-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('booking_inquiry', 'Booking Inquiry'), ('booking_update', 'Booking Update'), ('system', 'System Message')], default='text', max_length=20),
        ),
    ]
