# Generated by Django 5.2.6 on 2025-10-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_message_image_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('gif', 'GIF'), ('sticker', 'Sticker'), ('booking_inquiry', 'Booking Inquiry'), ('booking_update', 'Booking Update'), ('system', 'System Message')], default='text', max_length=20),
        ),
    ]
