# Generated by Django 5.2.6 on 2025-10-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('pay_later', 'Pay Later at Salon'), ('cash', 'Cash'), ('card', 'Card')], default='paypal', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('pay_later', 'Pay Later at Salon'), ('cash', 'Cash'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], default='paypal', max_length=20),
        ),
    ]
