# Generated by Django 4.2.7 on 2025-10-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_booking_google_calendar_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("pay_later", "Pay Later at Salon"),
                    ("cash", "Cash"),
                    ("card", "Card"),
                ],
                default="paypal",
                max_length=20,
            ),
        ),
    ]
