[build]
  base = "frontend"
  publish = "public"
  command = "echo 'Static site - no build required'"
  
# Skip all dependency installation
[build.processing]
  skip_processing = false

[build.environment]
  # Explicitly disable Python
  PYTHON_VERSION = ""
  # Disable dependency installation
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"
