[build]
  base = "frontend"
  publish = "frontend/public"
  command = "ls -la frontend/public"
  ignore = "/bin/false"

[build.environment]
  # Force Node.js environment (no Python)
  NODE_VERSION = "18"
  # Explicitly tell Netlify this is NOT a Python project
  PYTHON_VERSION = "false"
