[phases.setup]
nixPkgs = ["python312", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python manage.py migrate && gunicorn salon_booking.wsgi --config gunicorn.conf.py"

[variables]
PYTHONUNBUFFERED = "1"
