[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = ["python3.11 -m pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["cd backend && python3.11 manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python3.11 manage.py migrate && python3.11 -m gunicorn salon_booking.wsgi --bind 0.0.0.0:$PORT"
